spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:

  sql:
    init:
      data-locations: classpath*:sql/init_data.sql
      schema-locations: classpath*:sql/schema.sql