create table member (id bigint generated by default as identity, email varchar(100) not null, password varchar(50) not null, point integer not null, primary key (id));
create table point (id bigint generated by default as identity, action_at timestamp not null, amount integer not null, expire_at timestamp not null, status integer, member_id bigint, primary key (id));

alter table member add constraint UK_mbmcqelty0fbrvxp1q58dn57t unique (email);
alter table point add constraint FKbet7cyy000fgj8pm7pbuuur46 foreign key (member_id) references member;